"""Added legacy staff notes

Revision ID: 34a151505735
Revises: 242c1f9f1463
Create Date: 2023-12-05 21:49:08.019469+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34a151505735'
down_revision = '242c1f9f1463'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_configs',
                  sa.Column('legacy_threads',
                            sa.Boolean(),
                            nullable=False,
                            comment='Whether the server has legacy threads'),
                  schema='tickets_plus')
    op.alter_column('general_configs',
                    'first_autoclose',
                    existing_type=postgresql.INTERVAL(),
                    comment='Time since open with no response to auto-close',
                    existing_comment='Time since open with no response to autoclose',
                    existing_nullable=True,
                    schema='tickets_plus')
    op.alter_column('general_configs',
                    'any_autoclose',
                    existing_type=postgresql.INTERVAL(),
                    comment='Time since last response to auto-close',
                    existing_comment='Time since last response to autoclose',
                    existing_nullable=True,
                    schema='tickets_plus')
    op.alter_column(
        'general_configs',
        'helping_block',
        existing_type=sa.BIGINT(),
        comment=
        'Role to apply to users who are blocked from helping in tickets I would recommend also preventing the users from obtaining any other support roles. Using permissions checks in reaction bots. If not set, considered disabled.',
        existing_comment=
        'Role to apply to users who are blocked from helping in tickets I would reccomend also preventing the users from obtaining any other support roles. Using permissions checks in reaction bots. If not set, considered disabled.',
        existing_nullable=True,
        schema='tickets_plus')
    op.create_table_comment(
        'staff_roles',
        'Roles that are allowed to view ticket notes, and have access to staff commands.',
        existing_comment='Roles that are allowed to view ticket notes, and have acess to staff commands.',
        schema='tickets_plus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'staff_roles',
        'Roles that are allowed to view ticket notes, and have acess to staff commands.',
        existing_comment='Roles that are allowed to view ticket notes, and have access to staff commands.',
        schema='tickets_plus')
    op.alter_column(
        'general_configs',
        'helping_block',
        existing_type=sa.BIGINT(),
        comment=
        'Role to apply to users who are blocked from helping in tickets I would reccomend also preventing the users from obtaining any other support roles. Using permissions checks in reaction bots. If not set, considered disabled.',
        existing_comment=
        'Role to apply to users who are blocked from helping in tickets I would recommend also preventing the users from obtaining any other support roles. Using permissions checks in reaction bots. If not set, considered disabled.',
        existing_nullable=True,
        schema='tickets_plus')
    op.alter_column('general_configs',
                    'any_autoclose',
                    existing_type=postgresql.INTERVAL(),
                    comment='Time since last response to autoclose',
                    existing_comment='Time since last response to auto-close',
                    existing_nullable=True,
                    schema='tickets_plus')
    op.alter_column('general_configs',
                    'first_autoclose',
                    existing_type=postgresql.INTERVAL(),
                    comment='Time since open with no response to autoclose',
                    existing_comment='Time since open with no response to auto-close',
                    existing_nullable=True,
                    schema='tickets_plus')
    op.drop_column('general_configs', 'legacy_threads', schema='tickets_plus')
    # ### end Alembic commands ###
