"""v0.1.0.1 database

Revision ID: ae5d2cc3d90b
Revises:
Create Date: 2023-03-23 18:03:24.062078+00:00

"""
# pylint: disable=line-too-long
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ae5d2cc3d90b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'general_configs',
        sa.Column('any_autoclose',
                  sa.Integer(),
                  nullable=True,
                  comment='Number of minutes since last response to autoclose'),
        schema='tickets_plus')
    op.add_column(
        'general_configs',
        sa.Column(
            'support_block',
            sa.BigInteger(),
            nullable=True,
            comment=
            'Role to apply to users who are blocked from creating tickets Please manually add this role to blacklist users on https://ticketsbot.net/ If not set, considered disabled.'
        ),
        schema='tickets_plus')
    op.add_column(
        'general_configs',
        sa.Column(
            'helping_block',
            sa.BigInteger(),
            nullable=True,
            comment=
            'Role to apply to users who are blocked from helping in tickets I would reccomend also preventing the users from obtaining any other support roles. Using permissions checks in reaction bots. If not set, considered disabled.'
        ),
        schema='tickets_plus')
    op.add_column(
        'general_configs',
        sa.Column(
            'strip_roles',
            sa.Boolean(),
            comment='Whether to strip comsup roles when applying a helping_block'
        ),
        schema='tickets_plus')
    op.execute('UPDATE tickets_plus.general_configs SET strip_roles = FALSE')
    op.alter_column('general_configs',
                    'strip_roles',
                    nullable=False,
                    schema='tickets_plus')
    op.add_column(
        'members',
        sa.Column(
            'status',
            sa.Integer(),
            default=0,
            nullable=False,
            comment=
            'The status of the member, 0 is normal, 1 is support-blocked, 2 is barred from providing support'
        ),
        schema='tickets_plus')
    op.add_column(
        'members',
        sa.Column(
            'status_till',
            sa.DateTime(),
            nullable=True,
            comment=
            'The time until the status is removed, if None, the status is permanent'
        ),
        schema='tickets_plus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'status_till', schema='tickets_plus')
    op.drop_column('members', 'status', schema='tickets_plus')
    op.drop_column('general_configs', 'strip_roles', schema='tickets_plus')
    op.drop_column('general_configs', 'helping_block', schema='tickets_plus')
    op.drop_column('general_configs', 'support_block', schema='tickets_plus')
    op.drop_column('general_configs', 'any_autoclose', schema='tickets_plus')
    # ### end Alembic commands ###
